security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        admin_provider:
            entity:
                class: App\Entity\Admin
                property: email
        veterinary_provider:
            entity:
                class: App\Entity\Veterinary
                property: email
        employe_provider:
            entity:
                class: App\Entity\Employe
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            provider: admin_provider
            pattern: ^/admin
            lazy: true
            custom_authenticator: App\Security\SecurityAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

        veterinary:
            provider: veterinary_provider
            pattern: ^/veterinary
            lazy: true
            custom_authenticator: App\Security\SecurityAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

        employe:
            provider: employe_provider
            pattern: ^/employe
            lazy: true
            custom_authenticator: App\Security\SecurityAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

        main:
            lazy: true
            provider: admin_provider
            custom_authenticator: App\Security\SecurityAuthenticator
            logout:
                path: app_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: true

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/veterinary, roles: ROLE_VETERINARY }
        - { path: ^/employe, roles: ROLE_EMPLOYE }
when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
