controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\HomeController::index

admin_employees:
    path: /admin/employees
    controller: App\Controller\AdminController::employees

admin_veterinaries:
    path: /admin/veterinaries
    controller: App\Controller\AdminController::veterinaryList

admin_veterinary_new:
    path: /admin/veterinary/new
    controller: App\Controller\AdminController::addVeterinary
    methods: ['GET', 'POST']

admin_veterinary_edit:
    path: /admin/veterinary/{id}/edit
    controller: App\Controller\AdminController::editVeterinary

admin_veterinary_delete:
    path: /admin/veterinary/{id}
    controller: App\Controller\AdminController::deleteVeterinary
    methods: ['POST']

area1:
    path: /area1
    controller: App\Controller\AreaController::area1

area2:
    path: /area2
    controller: App\Controller\AreaController::area2

area3:
    path: /area3
    controller: App\Controller\AreaController::area3